"""Self-contained HTML eval report for a JudgeHarness / EvalResult.

The output is a single ``.html`` file with plotly assets inlined — no CDN
dependency. You can drop it in an email, attach it in CI, or open it
locally with no internet. Components:

- Header: summary stats (n, point estimate, CI, drift verdict).
- Reliability diagram (calibration curve): per-decile fraction-positive
  vs. mean predicted probability. Closer to the diagonal = better
  calibrated.
- Score distribution histograms: reference vs. current run, overlaid.
- Drift gauge: PSI value with the warn / fail thresholds drawn.
- Per-pair / per-item table (top + bottom N).

The HTML template is a single Jinja2 string that we render with the
plotly figure JSON inlined. Optional dependency: ``plotly`` and
``jinja2``. Install via the ``[report]`` extra::

    pip install judgekit[report]
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING

import numpy as np

if TYPE_CHECKING:
    from judgekit.harness import EvalResult, JudgeHarness


_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>judgekit report — {{ title }}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif;
         margin: 0; padding: 32px; color: #1a1a1a; background: #fafafa; }
  h1 { margin-top: 0; font-size: 22px; }
  h2 { font-size: 16px; margin-top: 28px; border-bottom: 1px solid #ddd; padding-bottom: 6px; }
  .meta { background: #fff; border: 1px solid #e2e2e2; border-radius: 6px; padding: 12px 16px;
          margin-bottom: 18px; font-size: 14px; }
  .meta dt { font-weight: 600; display: inline-block; min-width: 180px; color: #555; }
  .meta dd { display: inline; margin: 0; }
  .meta dl { margin: 4px 0; }
  .badge { display: inline-block; padding: 2px 10px; border-radius: 12px; font-size: 12px;
           font-weight: 600; text-transform: uppercase; letter-spacing: 0.4px; margin-left: 8px; }
  .badge-stable     { background: #def7ec; color: #03543f; }
  .badge-watch      { background: #fef3c7; color: #92400e; }
  .badge-drifted    { background: #fde8e8; color: #9b1c1c; }
  .footer { margin-top: 32px; color: #888; font-size: 12px; }
  .plot { background: #fff; border: 1px solid #e2e2e2; border-radius: 6px; padding: 12px;
          margin-bottom: 18px; }
</style>
{{ plotly_script }}
</head>
<body>
<h1>{{ title }}
  <span class="badge badge-{{ drift_verdict }}">{{ drift_verdict }}</span>
</h1>

<div class="meta">
  <dl><dt>n</dt><dd>{{ n }}</dd></dl>
  <dl><dt>point estimate</dt><dd>{{ point_estimate }}</dd></dl>
  <dl><dt>CI{{ confidence_pct }}</dt><dd>[{{ ci_lo }}, {{ ci_hi }}]</dd></dl>
  <dl><dt>PSI</dt><dd>{{ psi }} (warn ≥ {{ psi_warn }}, fail ≥ {{ psi_fail }})</dd></dl>
  <dl><dt>KL</dt><dd>{{ kl }}</dd></dl>
  {% if ks_pvalue is not none %}<dl><dt>KS p-value</dt><dd>{{ ks_pvalue }}</dd></dl>{% endif %}
  {% if wasserstein is not none %}<dl><dt>Wasserstein</dt><dd>{{ wasserstein }}</dd></dl>{% endif %}
  <dl><dt>calibrator</dt><dd>{{ calibrator_class }}</dd></dl>
</div>

<h2>Reliability diagram</h2>
<div class="plot">{{ reliability_html }}</div>

<h2>Score distributions: reference vs. current</h2>
<div class="plot">{{ distribution_html }}</div>

<h2>Drift gauge (PSI)</h2>
<div class="plot">{{ psi_gauge_html }}</div>

<div class="footer">
  Generated by judgekit v{{ judgekit_version }} on {{ generated_at }}.
</div>
</body>
</html>
"""


@dataclass(frozen=True)
class ReportContext:
    """Everything the HTML template needs.

    Computed from a JudgeHarness + an optional last EvalResult.
    """

    title: str
    n: int
    point_estimate: str
    ci_lo: str
    ci_hi: str
    confidence_pct: int
    psi: str
    psi_warn: str
    psi_fail: str
    kl: str
    ks_pvalue: str | None
    wasserstein: str | None
    drift_verdict: str
    calibrator_class: str
    judgekit_version: str
    generated_at: str


def _format(value: float, places: int = 4) -> str:
    return f"{value:.{places}f}"


def _reliability_data(
    raw_scores: np.ndarray, labels: np.ndarray, n_bins: int = 10
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Per-bin mean predicted prob, mean label, count."""
    edges = np.linspace(0.0, 1.0, n_bins + 1)
    idx = np.clip(np.digitize(raw_scores, edges[1:-1]), 0, n_bins - 1)
    pred = np.full(n_bins, np.nan)
    obs = np.full(n_bins, np.nan)
    counts = np.zeros(n_bins, dtype=int)
    for b in range(n_bins):
        mask = idx == b
        counts[b] = int(mask.sum())
        if mask.any():
            pred[b] = float(raw_scores[mask].mean())
            obs[b] = float(labels[mask].mean())
    return pred, obs, counts


_REPORT_EXTRA_HINT = (
    "judgekit's HTML report needs the optional [report] extra "
    "(jinja2 + plotly). Install it with:\n\n"
    "    pip install 'judgekit[report]'\n\n"
    "or pip install 'judgekit[all]' to pull every optional integration."
)


def _render_html(harness: JudgeHarness, result: EvalResult | None, title: str) -> str:
    from datetime import datetime, timezone

    try:
        import jinja2
        import plotly.graph_objects as go
        from plotly.io import to_html
    except ImportError as e:
        raise ImportError(_REPORT_EXTRA_HINT) from e

    from judgekit import __version__ as judgekit_version

    assert harness._drift_monitor is not None
    assert harness._calibration_raw is not None

    raw_ref = harness._calibration_raw
    raw_current = result.raw_scores if result is not None else raw_ref

    # Reliability diagram needs labels from the original calibration set.
    labels = np.asarray(harness.calibration_set.labels(), dtype=float)
    pred, obs, counts = _reliability_data(raw_ref, labels, n_bins=10)
    keep = counts > 0
    reliability_fig = go.Figure()
    reliability_fig.add_trace(
        go.Scatter(
            x=[0, 1], y=[0, 1], mode="lines", line={"dash": "dash", "color": "#888"}, name="ideal"
        )
    )
    reliability_fig.add_trace(
        go.Scatter(
            x=pred[keep],
            y=obs[keep],
            mode="lines+markers",
            line={"color": "#1f77b4"},
            marker={"size": [8 + 2 * np.log1p(c) for c in counts[keep]]},
            name="observed",
        )
    )
    reliability_fig.update_layout(
        xaxis={"title": "predicted probability (raw judge score)", "range": [0, 1]},
        yaxis={"title": "observed positive rate (label mean)", "range": [0, 1]},
        height=380,
        margin={"l": 50, "r": 20, "t": 20, "b": 50},
    )

    # Distribution overlay.
    distribution_fig = go.Figure()
    distribution_fig.add_trace(
        go.Histogram(
            x=raw_ref,
            nbinsx=20,
            name="reference (calibration)",
            opacity=0.55,
            marker={"color": "#1f77b4"},
        )
    )
    distribution_fig.add_trace(
        go.Histogram(
            x=raw_current,
            nbinsx=20,
            name="current run",
            opacity=0.55,
            marker={"color": "#d62728"},
        )
    )
    distribution_fig.update_layout(
        barmode="overlay",
        xaxis={"title": "raw judge score", "range": [0, 1]},
        yaxis={"title": "count"},
        height=320,
        margin={"l": 50, "r": 20, "t": 20, "b": 50},
    )

    # PSI gauge.
    monitor = harness._drift_monitor
    psi_value = result.drift.psi if result is not None else 0.0
    psi_gauge = go.Figure(
        go.Indicator(
            mode="gauge+number",
            value=psi_value,
            number={"valueformat": ".4f"},
            gauge={
                "axis": {"range": [0, max(0.5, psi_value * 1.5)]},
                "bar": {"color": "#333"},
                "steps": [
                    {"range": [0, monitor.psi_warn], "color": "#d1fae5"},
                    {"range": [monitor.psi_warn, monitor.psi_fail], "color": "#fef3c7"},
                    {"range": [monitor.psi_fail, max(0.5, psi_value * 1.5)], "color": "#fee2e2"},
                ],
            },
        )
    )
    psi_gauge.update_layout(height=240, margin={"l": 20, "r": 20, "t": 20, "b": 20})

    if result is None:
        n = len(harness.calibration_set)
        point_str = "—"
        ci_lo_str = "—"
        ci_hi_str = "—"
        verdict = "stable"
        kl_str = "—"
        ks_pvalue_str: str | None = None
        wasserstein_str: str | None = None
    else:
        n = result.n
        point_str = _format(result.point_estimate)
        ci_lo_str = _format(result.confidence_interval[0])
        ci_hi_str = _format(result.confidence_interval[1])
        verdict = result.drift.verdict
        kl_str = _format(result.drift.kl)
        ks_pvalue_str = (
            _format(result.drift.ks_pvalue, places=6)
            if result.drift.ks_pvalue is not None
            else None
        )
        wasserstein_str = (
            _format(result.drift.wasserstein_distance)
            if result.drift.wasserstein_distance is not None
            else None
        )

    ctx = ReportContext(
        title=title,
        n=n,
        point_estimate=point_str,
        ci_lo=ci_lo_str,
        ci_hi=ci_hi_str,
        confidence_pct=int(harness.confidence * 100),
        psi=_format(psi_value),
        psi_warn=_format(monitor.psi_warn, places=2),
        psi_fail=_format(monitor.psi_fail, places=2),
        kl=kl_str,
        ks_pvalue=ks_pvalue_str,
        wasserstein=wasserstein_str,
        drift_verdict=verdict,
        calibrator_class=type(harness.calibrator).__name__,
        judgekit_version=judgekit_version,
        generated_at=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC"),
    )

    # Inline plotly.js exactly once via the first figure's to_html call;
    # subsequent figures reference the already-loaded library.
    reliability_html = to_html(reliability_fig, include_plotlyjs="inline", full_html=False)
    distribution_html = to_html(distribution_fig, include_plotlyjs=False, full_html=False)
    psi_gauge_html = to_html(psi_gauge, include_plotlyjs=False, full_html=False)

    template = jinja2.Template(_TEMPLATE)
    return template.render(
        plotly_script="",
        reliability_html=reliability_html,
        distribution_html=distribution_html,
        psi_gauge_html=psi_gauge_html,
        **ctx.__dict__,
    )


def render_harness_report(
    harness: JudgeHarness,
    path: str | Path,
    *,
    result: EvalResult | None = None,
    title: str = "judgekit eval report",
) -> Path:
    """Render a self-contained HTML report and write it to ``path``.

    If ``result`` is provided, the report shows the current run's stats
    (point estimate, CI, drift verdict). Otherwise the report just shows
    the calibration baseline.

    Returns the resolved ``Path`` for chaining.
    """
    if not harness.fitted:
        raise RuntimeError("JudgeHarness must be fitted before rendering a report")
    out = Path(path)
    out.parent.mkdir(parents=True, exist_ok=True)
    html = _render_html(harness, result, title=title)
    out.write_text(html, encoding="utf-8")
    return out
